site_name: Google Docs guide


nav:
  - Functions of Google Docs:
    - Create Google documents: functions-of-google-docs/create-google-documents.md
    - Manage access to Google documents: functions-of-google-docs/manage-access-to-google-documents.md
    - Manage page settings: functions-of-google-docs/manage-page-settings.md
    - Format text: functions-of-google-docs/format-text.md
    - Insert different types of content: functions-of-google-docs/insert-different-types-of-content.md
    - Manage add-ons: functions-of-google-docs/manage-add-ons.md
    


theme:
    name: material
    logo: assets/google-docs-logo.png
    palette:
      primary: white

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences